name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  github-metrics:
    permissions:
      contents: write     # Required to push to another branch
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}

          # Output directory
          output_action: commit
          committer_branch: output
          committer_message: "chore: update GitHub metrics"

          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, collaborator

          config_display: large
          config_theme: dracula
          config_timezone: Asia/Kolkata
          config_twemoji: yes

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_lines: yes
          plugin_lines_history_limit: 1

      - name: Push metrics to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
